#!/bin/sh

# THIS FILE WILL ONLY LINT OPENED FILES
JS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
SCSS_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".scss")
PUG_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".pug")

if [[ "$JS_STAGED_FILES" = "" && "$SCSS_STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript and Scss:\n"

# Check for eslint
which node_modules/eslint/bin/eslint.js &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install ESlint\033[0m"
  exit 1
fi

for FILE in $JS_STAGED_FILES
do
  node_modules/eslint/bin/eslint.js "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mESLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mESLint Failed: $FILE\033[0m"
    PASS=false
  fi
done

for FILE in $SCSS_STAGED_FILES
do
  node_modules/sass-lint/bin/sass-lint.js -v -c .sass-lint.yml "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mSASSLint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mSASSLint Failed: $FILE\033[0m"
    PASS=false
  fi
done


for FILE in $PUG_STAGED_FILES
do
  node_modules/pug-lint/bin/pug-lint -c .pug-lintrc "$FILE"
  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mPug Lint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mPug Lint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m \n Your commit contains files that should pass lint tests but do not. \n Please fix or explicitly ignore the linter errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
